### ISSUE TITLE
Pipeline Action support for multiple index pages

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-pipeline-action#12]
@dev-aravind Please design an enhancement to the Artsdata Pipeline Action that would allow multiple `page-url`  and `entity-identifier` to be crawled for the same artifact.

The test case can be with theplayhouse-ca which has 2 sitemaps: https://theplayhouse.ca/fr/sitemap.xml and https://theplayhouse.ca/en/sitemap.xml.  The idea is to load all pages from both sitemaps into the artifact `orion/theplayhouse-ca`

**Comment by dev-aravind** [comment]
@saumier I propose this design. Let me know what you think.

```
with:
  mode: "fetch-push"
  artifact: "artifact123"
  publisher: "${{ secrets.PUBLISHER_URI_GREGORY }}"
  downloadFile: "file.jsonld"
  page-url: '["www.example.com/events", "www.example.com/evenements]'
  entity-identifier: '["identifier1", "identifier2"]'
  token: "${{ secrets.GITHUB_TOKEN }}"
```
